const fs = require('fs')

var mensagens = ["Por favor, aguarde um momento...",
    "Oi princesa, já estou preparando pra enviar, Aguarde..",
    "Salve mano, só aguarde um pouquinho que já estou enviando!!",
    "Aquieta o coração amigo, já estou enviando!",
    "Espere sentado que estou enviando!",
    "Pisa no freio aí amigo, tô enfiando já, ops enviando rsrs!",
    "Foi daqui que pediram comando? Ta chegando...",
    "O que você não pede chorando, que eu não faço sorrindo, enviando já!",
    "Em 365 dias úteis termino o comando kkkk meme, to enviando!",
    "Não precisa gritar, já ouvi e tô enviando seu pedido!",
    "Aproveita que tô terminando aqui e beba água, hidrate-se!",
    "Seu pedido é uma ordem, terminando patrão!",
    "Manda quem pode, obedece quem tem juízo. Já tô enviando...",
    "Jaja está na mão amigo, aguarde um instante!",
    "Quem espera, sempre alcança",
    "Tô enviando já amigão!",
    "Eitaa parece que alguém precisa de mim hehe‍!",
    "Tô com preguiça, mas calma aí!",
    "Por favor, aguarde um momento enquanto eu preparo a mágica!",
    "Oi, estou trabalhando nos bastidores, só mais um instante!",
    "Salve aí! Só estou ajustando as engrenagens, aguarde...",
    "Segura aí, estou quase terminando a mágica dos códigos!",
    "Pode relaxar, estou acelerando o processamento para você!",
    "Enquanto isso, estou preparando a poção mágica dos comandos.",
    "Seja paciente, o melhor está a caminho, prometo!",
    "Estou nos ajustes finais, aguarde um instante, por favor.",
    "Calma aí, estou afiando as ferramentas mágicas dos códigos!",
    "Aguarde com tranquilidade, estou costurando o comando perfeito.",
    "A paciência é uma virtude, e você está quase lá!",
    "Estou dando os toques finais, sua solicitação está quase pronta!",
    "Fique tranquilo, estou polindo o comando para você.",
    "Aguarde com calma, estou no controle da situação!",
    "Estou dando os retoques finais, sua solicitação será atendida em breve!",
    "Sua espera será recompensada, estou quase pronto!",
    "Relaxe, estou preparando o comando com carinho.",
    "Só mais um momento, e você terá o comando desejado!",
    "Enquanto isso, estou ajustando as engrenagens dos códigos.",
    "Segura a ansiedade, a mágica está acontecendo!",
    "Aguarde com paciência, estou trabalhando nos detalhes.",
    "A espera está quase no fim, sua solicitação está próxima.",
    "Sinta-se especial, sua solicitação está sendo cuidadosamente processada.",
    "Não se preocupe, estou fazendo a mágica acontecer nos bastidores!",
    "Estou no comando, e você está prestes a receber o seu.",
    "Aguarde com paciência, o melhor está a caminho.",
    "Estou processando com carinho, só mais um instante.",
    "Em breve, a sua solicitação estará pronta para ser entregue!",
    "A paciência é a chave, e você está quase lá!",
    "Estou dando os toques finais, logo você terá o que pediu.",
    "Aguarde com tranquilidade, a mágica está acontecendo.",
    "Estou no controle da situação, aguarde só mais um pouco.",
    "Em breve, sua solicitação estará disponível.",
    "Sua paciência será recompensada, estou finalizando o comando!",
   "acalma o cu ai meu bem ja estou trazendo seu comando😘",
   "calma bb ja estou trazendo seu comando😎✨",
   "espere alguns minutos ai meu chapa",
   "ja estou trabalhando aqui para trazer o seu pedido",
   "o que você quer tá mole heheh",
   "pedrozz domina o senário fiot😎👑",
   "espere um momento ",
   "calma ai",
   "calma la mn🥴",
   "calma qi trouxa kkk"
    ]


module.exports = {
mensagens
}
